#pragma once

#define GFX_VERSION_MAJOR 0
#define GFX_VERSION_MINOR 1
#define GFX_VERSION_PATCH 0

#ifdef _WIN32
        #define DLL_EXPORT __declspec(dllexport)
        #define DLL_IMPORT __declspec(dllimport)
#else
        #define DLL_EXPORT __attribute__((visibility("default")))
        #define DLL_IMPORT __attribute__((visibility("default")))
#endif

#ifdef GFX_EXPORTS
    #define GFX_API DLL_EXPORT
#else
    #define GFX_API DLL_IMPORT
#endif

namespace gfx
{
    constexpr const char GFX[] = "GFX BUILD";
    constexpr const char GL[] = "OPENGL";
    constexpr const char BINDLES_TEXTURE[] = "GL_ARB_bindless_texture";

    // ASSIMP WRAPPERS
    constexpr auto CONFIG_GLOB_MEASURE_TIME = "GLOB_MEASURE_TIME";
    constexpr auto CONFIG_IMPORT_NO_SKELETON_MESHES = "IMPORT_NO_SKELETON_MESHES";
    constexpr auto CONFIG_PP_SBBC_MAX_BONES = "PP_SBBC_MAX_BONES";
    constexpr auto CONFIG_PP_CT_MAX_SMOOTHING_ANGLE = "PP_CT_MAX_SMOOTHING_ANGLE";
    constexpr auto CONFIG_PP_CT_TEXTURE_CHANNEL_INDEX = "PP_CT_TEXTURE_CHANNEL_INDEX";
    constexpr auto CONFIG_PP_GSN_MAX_SMOOTHING_ANGLE = "PP_GSN_MAX_SMOOTHING_ANGLE";
    constexpr auto CONFIG_IMPORT_MDL_COLORMAP = "IMPORT_MDL_COLORMAP";
    constexpr auto CONFIG_PP_RRM_EXCLUDE_LIST = "PP_RRM_EXCLUDE_LIST";
    constexpr auto CONFIG_PP_PTV_KEEP_HIERARCHY = "PP_PTV_KEEP_HIERARCHY";
    constexpr auto CONFIG_PP_PTV_NORMALIZE = "PP_PTV_NORMALIZE";
    constexpr auto CONFIG_PP_PTV_ADD_ROOT_TRANSFORMATION = "PP_PTV_ADD_ROOT_TRANSFORMATION";
    constexpr auto CONFIG_PP_PTV_ROOT_TRANSFORMATION = "PP_PTV_ROOT_TRANSFORMATION";
    constexpr auto CONFIG_CHECK_IDENTITY_MATRIX_EPSILON = "CHECK_IDENTITY_MATRIX_EPSILON";
    constexpr auto CONFIG_PP_FD_REMOVE = "PP_FD_REMOVE";
    constexpr auto CONFIG_PP_FD_CHECKAREA = "PP_FD_CHECKAREA";
    constexpr auto CONFIG_PP_OG_EXCLUDE_LIST = "PP_OG_EXCLUDE_LIST";
    constexpr auto CONFIG_PP_SLM_TRIANGLE_LIMIT = "PP_SLM_TRIANGLE_LIMIT";
    constexpr auto CONFIG_PP_SLM_VERTEX_LIMIT = "PP_SLM_VERTEX_LIMIT";
    constexpr auto CONFIG_PP_LBW_MAX_WEIGHTS = "PP_LBW_MAX_WEIGHTS";
    constexpr auto CONFIG_PP_DB_THRESHOLD = "PP_DB_THRESHOLD";
    constexpr auto CONFIG_PP_DB_ALL_OR_NONE = "PP_DB_ALL_OR_NONE";
    constexpr auto CONFIG_PP_ICL_PTCACHE_SIZE = "PP_ICL_PTCACHE_SIZE";
    constexpr auto CONFIG_PP_RVC_FLAGS = "PP_RVC_FLAGS";
    constexpr auto CONFIG_PP_SBP_REMOVE = "PP_SBP_REMOVE";
    constexpr auto CONFIG_PP_FID_ANIM_ACCURACY = "PP_FID_ANIM_ACCURACY";
    constexpr auto CONFIG_PP_FID_IGNORE_TEXTURECOORDS = "PP_FID_IGNORE_TEXTURECOORDS";
    constexpr auto CONFIG_PP_TUV_EVALUATE = "PP_TUV_EVALUATE";
    constexpr auto CONFIG_FAVOUR_SPEED = "FAVOUR_SPEED";
    constexpr auto CONFIG_IMPORT_SCHEMA_DOCUMENT_PROVIDER = "IMPORT_SCHEMA_DOCUMENT_PROVIDER";
    constexpr auto CONFIG_IMPORT_FBX_READ_ALL_GEOMETRY_LAYERS = "IMPORT_FBX_READ_ALL_GEOMETRY_LAYERS";
    constexpr auto CONFIG_IMPORT_FBX_READ_ALL_MATERIALS = "IMPORT_FBX_READ_ALL_MATERIALS";
    constexpr auto CONFIG_IMPORT_FBX_READ_MATERIALS = "IMPORT_FBX_READ_MATERIALS";
    constexpr auto CONFIG_IMPORT_FBX_READ_TEXTURES = "IMPORT_FBX_READ_TEXTURES";
    constexpr auto CONFIG_IMPORT_FBX_READ_CAMERAS = "IMPORT_FBX_READ_CAMERAS";
    constexpr auto CONFIG_IMPORT_FBX_READ_LIGHTS = "IMPORT_FBX_READ_LIGHTS";
    constexpr auto CONFIG_IMPORT_FBX_READ_ANIMATIONS = "IMPORT_FBX_READ_ANIMATIONS";
    constexpr auto CONFIG_IMPORT_FBX_READ_WEIGHTS = "IMPORT_FBX_READ_WEIGHTS";
    constexpr auto CONFIG_IMPORT_FBX_STRICT_MODE = "IMPORT_FBX_STRICT_MODE";
    constexpr auto CONFIG_IMPORT_FBX_PRESERVE_PIVOTS = "IMPORT_FBX_PRESERVE_PIVOTS";
    constexpr auto CONFIG_IMPORT_FBX_OPTIMIZE_EMPTY_ANIMATION_CURVES = "IMPORT_FBX_OPTIMIZE_EMPTY_ANIMATION_CURVES";
    constexpr auto CONFIG_IMPORT_FBX_EMBEDDED_TEXTURES_LEGACY_NAMING = "AI_CONFIG_IMPORT_FBX_EMBEDDED_TEXTURES_LEGACY_NAMING";
    constexpr auto CONFIG_IMPORT_REMOVE_EMPTY_BONES = "AI_CONFIG_IMPORT_REMOVE_EMPTY_BONES";
    constexpr auto CONFIG_FBX_CONVERT_TO_M = "AI_CONFIG_FBX_CONVERT_TO_M";
    constexpr auto CONFIG_IMPORT_FBX_IGNORE_UP_DIRECTION = "AI_CONFIG_IMPORT_FBX_IGNORE_UP_DIRECTION";
    constexpr auto CONFIG_FBX_USE_SKELETON_BONE_CONTAINER = "AI_CONFIG_FBX_USE_SKELETON_BONE_CONTAINER";
    constexpr auto CONFIG_IMPORT_GLOBAL_KEYFRAME = "IMPORT_GLOBAL_KEYFRAME";
    constexpr auto CONFIG_IMPORT_MD3_KEYFRAME = "IMPORT_MD3_KEYFRAME";
    constexpr auto CONFIG_IMPORT_MD2_KEYFRAME = "IMPORT_MD2_KEYFRAME";
    constexpr auto CONFIG_IMPORT_MDL_KEYFRAME = "IMPORT_MDL_KEYFRAME";
    constexpr auto CONFIG_IMPORT_MDC_KEYFRAME = "IMPORT_MDC_KEYFRAME";
    constexpr auto CONFIG_IMPORT_SMD_KEYFRAME = "IMPORT_SMD_KEYFRAME";
    constexpr auto CONFIG_IMPORT_UNREAL_KEYFRAME = "IMPORT_UNREAL_KEYFRAME";
    constexpr auto CONFIG_IMPORT_MDL_HL1_READ_ANIMATIONS = "IMPORT_MDL_HL1_READ_ANIMATIONS";
    constexpr auto CONFIG_IMPORT_MDL_HL1_READ_ANIMATION_EVENTS = "IMPORT_MDL_HL1_READ_ANIMATION_EVENTS";
    constexpr auto CONFIG_IMPORT_MDL_HL1_TRANSFORM_COORD_SYSTEM = "TRANSFORM COORDSYSTEM FOR HS! MODELS";
    constexpr auto CONFIG_IMPORT_MDL_HL1_READ_BLEND_CONTROLLERS = "IMPORT_MDL_HL1_READ_BLEND_CONTROLLERS";
    constexpr auto CONFIG_IMPORT_MDL_HL1_READ_SEQUENCE_TRANSITIONS = "IMPORT_MDL_HL1_READ_SEQUENCE_TRANSITIONS";
    constexpr auto CONFIG_IMPORT_MDL_HL1_READ_ATTACHMENTS = "IMPORT_MDL_HL1_READ_ATTACHMENTS";
    constexpr auto CONFIG_IMPORT_MDL_HL1_READ_BONE_CONTROLLERS = "IMPORT_MDL_HL1_READ_BONE_CONTROLLERS";
    constexpr auto CONFIG_IMPORT_MDL_HL1_READ_HITBOXES = "IMPORT_MDL_HL1_READ_HITBOXES";
    constexpr auto CONFIG_IMPORT_MDL_HL1_READ_MISC_GLOBAL_INFO = "IMPORT_MDL_HL1_READ_MISC_GLOBAL_INFO";
    constexpr auto CONFIG_IMPORT_SMD_LOAD_ANIMATION_LIST = "IMPORT_SMD_LOAD_ANIMATION_LIST";
    constexpr auto CONFIG_IMPORT_AC_SEPARATE_BFCULL = "IMPORT_AC_SEPARATE_BFCULL";
    constexpr auto CONFIG_IMPORT_AC_EVAL_SUBDIVISION = "IMPORT_AC_EVAL_SUBDIVISION";
    constexpr auto CONFIG_IMPORT_UNREAL_HANDLE_FLAGS = "UNREAL_HANDLE_FLAGS";
    constexpr auto CONFIG_IMPORT_TER_MAKE_UVS = "IMPORT_TER_MAKE_UVS";
    constexpr auto CONFIG_IMPORT_ASE_RECONSTRUCT_NORMALS = "IMPORT_ASE_RECONSTRUCT_NORMALS";
    constexpr auto CONFIG_IMPORT_MD3_HANDLE_MULTIPART = "IMPORT_MD3_HANDLE_MULTIPART";
    constexpr auto CONFIG_IMPORT_MD3_SKIN_NAME = "IMPORT_MD3_SKIN_NAME";
    constexpr auto CONFIG_IMPORT_MD3_LOAD_SHADERS = "IMPORT_MD3_LOAD_SHADERS";
    constexpr auto CONFIG_IMPORT_MD3_SHADER_SRC = "IMPORT_MD3_SHADER_SRC";
    constexpr auto CONFIG_IMPORT_LWO_ONE_LAYER_ONLY = "IMPORT_LWO_ONE_LAYER_ONLY";
    constexpr auto CONFIG_IMPORT_MD5_NO_ANIM_AUTOLOAD = "IMPORT_MD5_NO_ANIM_AUTOLOAD";
    constexpr auto CONFIG_IMPORT_LWS_ANIM_START = "IMPORT_LWS_ANIM_START";
    constexpr auto CONFIG_IMPORT_LWS_ANIM_END = "IMPORT_LWS_ANIM_END";
    constexpr auto CONFIG_IMPORT_IRR_ANIM_FPS = "IMPORT_IRR_ANIM_FPS";
    constexpr auto CONFIG_IMPORT_OGRE_MATERIAL_FILE = "IMPORT_OGRE_MATERIAL_FILE";
    constexpr auto CONFIG_IMPORT_OGRE_TEXTURETYPE_FROM_FILENAME = "IMPORT_OGRE_TEXTURETYPE_FROM_FILENAME";
    constexpr auto CONFIG_ANDROID_JNI_ASSIMP_MANAGER_SUPPORT = "AI_CONFIG_ANDROID_JNI_ASSIMP_MANAGER_SUPPORT";
    constexpr auto CONFIG_IMPORT_IFC_SKIP_SPACE_REPRESENTATIONS = "IMPORT_IFC_SKIP_SPACE_REPRESENTATIONS";
    constexpr auto CONFIG_IMPORT_IFC_CUSTOM_TRIANGULATION = "IMPORT_IFC_CUSTOM_TRIANGULATION";
    constexpr auto CONFIG_IMPORT_IFC_SMOOTHING_ANGLE = "IMPORT_IFC_SMOOTHING_ANGLE";
    constexpr auto CONFIG_IMPORT_IFC_CYLINDRICAL_TESSELLATION = "IMPORT_IFC_CYLINDRICAL_TESSELLATION";
    constexpr auto CONFIG_IMPORT_COLLADA_IGNORE_UP_DIRECTION = "IMPORT_COLLADA_IGNORE_UP_DIRECTION";
    constexpr auto CONFIG_IMPORT_COLLADA_IGNORE_UNIT_SIZE = "IMPORT_COLLADA_IGNORE_UNIT_SIZE";
    constexpr auto CONFIG_IMPORT_COLLADA_USE_COLLADA_NAMES = "IMPORT_COLLADA_USE_COLLADA_NAMES";
    constexpr auto CONFIG_EXPORT_XFILE_64BIT = "EXPORT_XFILE_64BIT";
    constexpr auto CONFIG_EXPORT_POINT_CLOUDS = "EXPORT_POINT_CLOUDS";
    constexpr auto CONFIG_USE_GLTF_PBR_SPECULAR_GLOSSINESS = "USE_GLTF_PBR_SPECULAR_GLOSSINESS";
    constexpr auto CONFIG_EXPORT_GLTF_UNLIMITED_SKINNING_BONES_PER_VERTEX = "USE_UNLIMITED_BONES_PER VERTEX";
    constexpr auto CONFIG_EXPORT_FBX_TRANSPARENCY_FACTOR_REFER_TO_OPACITY = "EXPORT_FBX_TRANSPARENCY_FACTOR_REFER_TO_OPACITY";
    constexpr auto CONFIG_EXPORT_BLOB_NAME = "EXPORT_BLOB_NAME";
    constexpr auto CONFIG_GLOBAL_SCALE_FACTOR_KEY = "GLOBAL_SCALE_FACTOR";
    constexpr auto CONFIG_APP_SCALE_KEY = "APP_SCALE_FACTOR";
    // END ASSIMP WRAPPERS

    enum class TextureBindingMode
    {
        BINDLESS,
        BIND,
        NONE
    };
}